package cl.usach.gobierno.controllers;

import cl.usach.gobierno.Lucene;
import cl.usach.gobierno.entities.Political;
import cl.usach.gobierno.repositories.PoliticalRepository;
import com.mongodb.Block;
import com.mongodb.client.FindIterable;
import com.mongodb.client.model.Filters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import cl.usach.gobierno.MongoConnection;
import org.bson.Document;
import com.mongodb.client.MongoCollection;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


@RestController    // This means that this class is a Controller
@RequestMapping("/politicals")

public class politicalController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PoliticalRepository politicalRepository;


    @CrossOrigin
    @GetMapping(path="/")
    public @ResponseBody
    Iterable<Political> getAllPolitical() {
        // This returns a JSON or XML with the users
        return politicalRepository.findAll();
    }

    @CrossOrigin
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    @ResponseBody
    public ResponseEntity<Political> findOne(@PathVariable("id") Integer id){
        Political political = politicalRepository.findById(id);

        if (political == null){
            return new ResponseEntity<>(political, HttpStatus.NOT_FOUND);
        }else{
            return new ResponseEntity<>(political, HttpStatus.OK);
        }
    }

    @CrossOrigin
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    @ResponseBody
    public ResponseEntity<Political> deletePolitical(@PathVariable("id") Integer id){
        Political political = politicalRepository.findById(id);
        if (political == null){
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }else{
            politicalRepository.delete(political);
            return new ResponseEntity<>(HttpStatus.OK);
        }
    }

    @CrossOrigin
    @RequestMapping(value = "/{id}", method = RequestMethod.PUT)
    @ResponseBody
    public ResponseEntity<Political> editPolitical(@RequestBody Political resource, @PathVariable("id") Integer id){
        Political politicalOld = politicalRepository.findById(id);
        if (politicalOld == null) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }else{
            resource.setId(id);
            return new ResponseEntity<>(politicalRepository.save(resource), HttpStatus.OK);
        }
    }

    /**
     *  Obtiene el total de comentarios de Lucene
     *
     *  Realiza conexion a la ___ y obtiene datos,
     *  obtiene la cantidad de documentos que contienen en su variable la palabra analysis
     */
    @CrossOrigin
    @RequestMapping(value = "/{id}/total", method = RequestMethod.GET)
    @ResponseBody
    public ArrayList<Map> getTotal(@PathVariable("id") Integer id) {
        Political political = politicalRepository.findById(id);
        Lucene luca = new Lucene();
        ArrayList<Integer> aprobacion = new ArrayList<>();
        aprobacion = luca.getAnalysis(political.getNombre());
        ArrayList<Map> resultado = new ArrayList<>();
        Map<String, Object> result = new HashMap<String, Object>(2);

        result.put("aprobacion", "Positiva");
        result.put("numero", aprobacion.get(0));
        resultado.add(result);

        Map<String, Object> result2 = new HashMap<String, Object>(2);
        result2.put("aprobacion", "Negativa");
        result2.put("numero", aprobacion.get(1));
        resultado.add(result2);

        Map<String, Object> result3 = new HashMap<String, Object>(2);
        result3.put("aprobacion", "Neutra");
        result3.put("numero", aprobacion.get(2));
        resultado.add(result3);

        return resultado;
    }

    @CrossOrigin
    @RequestMapping(value = "/total/general", method = RequestMethod.GET)
    @ResponseBody
    public ArrayList<Map> getTotal() {

        Lucene luca = new Lucene();
        ArrayList<Integer> aprobacion = new ArrayList<>();
        aprobacion = luca.getAnalysisGeneral();
        ArrayList<Map> resultado = new ArrayList<>();
        Map<String, Object> result = new HashMap<String, Object>(2);

        result.put("aprobacion", "Positiva");
        result.put("numero", aprobacion.get(0));
        resultado.add(result);

        Map<String, Object> result2 = new HashMap<String, Object>(2);
        result2.put("aprobacion", "Negativa");
        result2.put("numero", aprobacion.get(1));
        resultado.add(result2);

        Map<String, Object> result3 = new HashMap<String, Object>(2);
        result3.put("aprobacion", "Neutra");
        result3.put("numero", aprobacion.get(2));
        resultado.add(result3);

        return resultado;
    }

    /**
     * PRUEBA
     * Realiza una conexion a mongodb y por cada documento imprime por pantalla
     * "Hola Mundo!" y la variable comentariosNegativos de cada documento de mongoDB
     * comentariosNegativos debe ser una variable del tipo String
     */
    @CrossOrigin
    @RequestMapping(value = "/test", method = RequestMethod.GET)
    @ResponseBody
    public int getTest(){
        MongoConnection mongo = MongoConnection.getMongo();
        mongo.OpenMongoClient();
        MongoCollection<Document> collection = mongo.getCollection();
        FindIterable<Document> cursor = collection.find();
        System.out.println("lei los tweets");

        cursor.forEach((Block<Document>) document -> {
            System.out.println("Hola Mundo!");
            String comentariosNegativos = document.getString("comentariosNegativos");
            System.out.println(comentariosNegativos);
        });
        return 0;
    }
}