-- MySQL Script generated by MySQL Workbench
-- vie 17 ago 2018 17:37:56 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gobierno
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gobierno` ;

-- -----------------------------------------------------
-- Schema gobierno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gobierno` DEFAULT CHARACTER SET utf8 ;
USE `gobierno` ;

-- -----------------------------------------------------
-- Table `gobierno`.`politicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`politicos` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`politicos` (
  `idpoliticos` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `cargo` VARCHAR(255) NULL,
  `fechainicio` DATE NULL,
  `fechatermino` DATE NULL,
  `compositivos` DOUBLE NULL,
  `comnegativos` DOUBLE NULL,
  `comneutros` DOUBLE NULL,
  PRIMARY KEY (`idpoliticos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`keywords` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`keywords` (
  `idkeywords` INT NOT NULL,
  `keywords` VARCHAR(255) NULL,
  PRIMARY KEY (`idkeywords`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`politicos_has_keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`politicos_has_keywords` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`politicos_has_keywords` (
  `politicos_idpoliticos` INT NOT NULL,
  `keywords_idkeywords` INT NOT NULL,
  PRIMARY KEY (`politicos_idpoliticos`, `keywords_idkeywords`),
  INDEX `fk_politicos_has_keywords_keywords1_idx` (`keywords_idkeywords` ASC),
  INDEX `fk_politicos_has_keywords_politicos1_idx` (`politicos_idpoliticos` ASC),
  CONSTRAINT `fk_politicos_has_keywords_politicos1`
    FOREIGN KEY (`politicos_idpoliticos`)
    REFERENCES `gobierno`.`politicos` (`idpoliticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_politicos_has_keywords_keywords1`
    FOREIGN KEY (`keywords_idkeywords`)
    REFERENCES `gobierno`.`keywords` (`idkeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gobierno`.`politicos`
-- -----------------------------------------------------
START TRANSACTION;
USE `gobierno`;
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (1, 'Sebastian Piñera', 'Presidente de la Republica', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (2, 'Andrés Chadwick', 'Ministerio del Interior y Seguridad Pública', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (3, 'Roberto Ampuero', 'MInisterio de Relaciones Exteriores', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (4, 'Alberto Espina', 'Ministerio de Defensa Nacional', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (5, 'Felipe Larraín Bascuñán', 'Ministerio de Hacienda', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (6, 'Gonzalo Blumel Mac Iver', 'MInisterio de Secretaría General de la Presidencia', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (7, 'Cecilia Pérez Jara', 'MInisterio de Secretaría General de Gobierno', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (8, 'José Ramón Valente VIas', 'Ministerio de Economía, Fomento y Turismo', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (9, 'Alfredo Moreno Charme', 'Ministerio de Desarrollo Social', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (10, 'Marcela Cubillos Sigall', 'Ministerio de Educación', '2018-08-09', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (11, 'Hernán Larraín Fernández', 'Ministerio de Justicia y Derechos Humanos', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (12, 'Nicolás Monckeberg Díaz', 'Ministerio de Trabajo y Previsión Social', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (13, 'Juan Andrés Fontainer Talavera', 'Ministerio de Obras Públicas', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (14, 'Emilio Santelices Cuevas', 'Ministerio de Salud', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (15, 'Cristián Monckeberg Bruner', 'MInisterio de Vivienda y Urbanismo', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (16, 'Antonio Walker Prieto', 'Ministerio de Agricultura', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (17, 'Baldo Prokurica Prokurica', 'Ministerio de Minería', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (18, 'Gloria Hutt Hesse', 'Ministerio de Transporte y Telecomunicaciones ', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (19, 'Felipe Ward Edwards', 'MInisterio de Bienes Nacionales', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (20, 'Susana Jiménez Schuster', 'Ministerio de Energía', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (21, 'Carolina Schmidt Zaldívar', 'Ministerio de Medio Ambiente', '2018-08-09', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (22, 'Pauline Kantor Pupkin', 'Ministerio de Deporte', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (23, 'Isabel Plá Jarufe', 'Ministerio de la Mujer y la Equidad de Género', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (24, 'Consuelo Valdés Chadwick', 'Ministerio de Culturas, las Artes y el Patrimonio', '2018-08-13', NULL, 0, 0, 0);

COMMIT;
