-- MySQL Script generated by MySQL Workbench
-- sáb 08 sep 2018 10:59:01 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gobierno
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gobierno` ;

-- -----------------------------------------------------
-- Schema gobierno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gobierno` DEFAULT CHARACTER SET utf8 ;
USE `gobierno` ;

-- -----------------------------------------------------
-- Table `gobierno`.`politicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`politicos` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`politicos` (
  `idpoliticos` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `cargo` VARCHAR(255) NULL,
  `fechainicio` DATE NULL,
  `fechatermino` DATE NULL,
  `compositivos` INT NULL,
  `comnegativos` INT NULL,
  `comneutros` INT NULL,
  PRIMARY KEY (`idpoliticos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`keywords` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`keywords` (
  `idkeywords` INT NOT NULL,
  `keywords` VARCHAR(255) NULL,
  PRIMARY KEY (`idkeywords`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`politicos_has_keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`politicos_has_keywords` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`politicos_has_keywords` (
  `politicos_idpoliticos` INT NOT NULL,
  `keywords_idkeywords` INT NOT NULL,
  PRIMARY KEY (`politicos_idpoliticos`, `keywords_idkeywords`),
  INDEX `fk_politicos_has_keywords_keywords1_idx` (`keywords_idkeywords` ASC),
  INDEX `fk_politicos_has_keywords_politicos1_idx` (`politicos_idpoliticos` ASC),
  CONSTRAINT `fk_politicos_has_keywords_politicos1`
    FOREIGN KEY (`politicos_idpoliticos`)
    REFERENCES `gobierno`.`politicos` (`idpoliticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_politicos_has_keywords_keywords1`
    FOREIGN KEY (`keywords_idkeywords`)
    REFERENCES `gobierno`.`keywords` (`idkeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`localidad` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`localidad` (
  `idlocalidad` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `isregion` BOOLEAN DEFAULT false,
  PRIMARY KEY (`idlocalidad`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `gobierno`.`politico_localidad` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`politico_localidad`(
	`idpoliticos` INT NOT NULL,
    `idlocalidad` INT NOT NULL,
    `compositivos` INT NULL,
	`comnegativos` INT NULL,
	`comneutros` INT NULL,
    PRIMARY KEY (`idpoliticos`, `idlocalidad`),
	INDEX `fk_politico_localidad_politicos1_idx` (`idpoliticos` ASC),
	INDEX `fk_politico_localidad_localidad1_idx` (`idlocalidad` ASC),
    CONSTRAINT `fk_politico_localidad_politicos1`
      FOREIGN KEY (`idpoliticos`)
      REFERENCES `gobierno`.`politicos` (`idpoliticos`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
	CONSTRAINT `fk_politico_localidad_localidad1`
	  FOREIGN KEY (`idlocalidad`)
	  REFERENCES `gobierno`.`localidad` (`idlocalidad`)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION)
ENGINE = InnoDB;
    


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gobierno`.`politicos`
-- -----------------------------------------------------
START TRANSACTION;
USE `gobierno`;
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (1, 'Sebastian Piñera', 'Presidente de la Republica', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (2, 'Andrés Chadwick', 'Ministerio del Interior y Seguridad Pública', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (3, 'Roberto Ampuero', 'Ministerio de Relaciones Exteriores', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (4, 'Alberto Espina', 'Ministerio de Defensa Nacional', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (5, 'Felipe Larraín Bascuñán', 'Ministerio de Hacienda', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (6, 'Gonzalo Blumel Mac Iver', 'MInisterio de Secretaría General de la Presidencia', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (7, 'Cecilia Pérez Jara', 'Ministerio de Secretaría General de Gobierno', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (8, 'José Ramón Valente Vias', 'Ministerio de Economía, Fomento y Turismo', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (9, 'Alfredo Moreno Charme', 'Ministerio de Desarrollo Social', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (10, 'Marcela Cubillos Sigall', 'Ministerio de Educación', '2018-08-09', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (11, 'Hernán Larraín Fernández', 'Ministerio de Justicia y Derechos Humanos', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (12, 'Nicolás Monckeberg Díaz', 'Ministerio de Trabajo y Previsión Social', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (13, 'Juan Andrés Fontainer Talavera', 'Ministerio de Obras Públicas', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (14, 'Emilio Santelices Cuevas', 'Ministerio de Salud', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (15, 'Cristián Monckeberg Bruner', 'Ministerio de Vivienda y Urbanismo', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (16, 'Antonio Walker Prieto', 'Ministerio de Agricultura', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (17, 'Baldo Prokurica Prokurica', 'Ministerio de Minería', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (18, 'Gloria Hutt Hesse', 'Ministerio de Transporte y Telecomunicaciones ', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (19, 'Felipe Ward Edwards', 'Ministerio de Bienes Nacionales', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (20, 'Susana Jiménez Schuster', 'Ministerio de Energía', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (21, 'Carolina Schmidt Zaldívar', 'Ministerio de Medio Ambiente', '2018-08-09', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (22, 'Pauline Kantor Pupkin', 'Ministerio de Deporte', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (23, 'Isabel Plá Jarufe', 'Ministerio de la Mujer y la Equidad de Género', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (24, 'Consuelo Valdés Chadwick', 'Ministerio de Culturas, las Artes y el Patrimonio', '2018-08-13', NULL, 0, 0, 0);

INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Metropolitana', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Arica y Parinacota', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Tarapacá', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Antofagasta', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Atacama', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Coquimbo', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Valparaíso', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ("Libertador General Bernardo O'Higgins", TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Maule', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('BioBío', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('La Araucanía', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Los Ríos', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Los Lagos', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Aysén del General Carlos Ibañez del Campo', TRUE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Magallanes', TRUE);

INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Santiago', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Cerrillos', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Cerro Navia', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Conchalí', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('El Bosque', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Estación Central', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Huechuraba', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ("Independencia", FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('La Cisterna', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('La Florida', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('La Granja', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('La Pintana', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('La Reina', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Las Condes', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Lo Barnechea', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Lo Espejo', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Lo Prado', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Macul', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Maipú', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Ñuñoa', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Pedro Aguirre Cerda', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Peñalolén', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Providencia', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Pudahuel', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Quilicura', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Quinta Normal', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Recoleta', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Renca', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('San Joaquín', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('San Miguel', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('San Ramón', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Vitacura', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Colina', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Lampa', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Til Til', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Puente Alto', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Pirque', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('San José de Maipo', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Buin', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Calera de Tango', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Buin', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Calera de Tango', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Paine', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Melipilla', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Alhué', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Curacaví', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('María Pinto', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('San Pedro', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Talagante', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('El Monte', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Isla de Maipo', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Padre Hurtado', FALSE);
INSERT INTO `gobierno`.`localidad` (`nombre`, `isRegion`) VALUES ('Peñaflor', FALSE);

COMMIT;
