-- MySQL Script generated by MySQL Workbench
-- sáb 08 sep 2018 10:59:01 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gobierno
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gobierno` ;

-- -----------------------------------------------------
-- Schema gobierno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gobierno` DEFAULT CHARACTER SET utf8 ;
USE `gobierno` ;

-- -----------------------------------------------------
-- Table `gobierno`.`politicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`politicos` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`politicos` (
  `idpoliticos` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `cargo` VARCHAR(255) NULL,
  `fechainicio` DATE NULL,
  `fechatermino` DATE NULL,
  `compositivos` INT NULL,
  `comnegativos` INT NULL,
  `comneutros` INT NULL,
  PRIMARY KEY (`idpoliticos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`keywords` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`keywords` (
  `idkeywords` INT NOT NULL,
  `keywords` VARCHAR(255) NULL,
  PRIMARY KEY (`idkeywords`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`politicos_has_keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`politicos_has_keywords` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`politicos_has_keywords` (
  `politicos_idpoliticos` INT NOT NULL,
  `keywords_idkeywords` INT NOT NULL,
  PRIMARY KEY (`politicos_idpoliticos`, `keywords_idkeywords`),
  INDEX `fk_politicos_has_keywords_keywords1_idx` (`keywords_idkeywords` ASC),
  INDEX `fk_politicos_has_keywords_politicos1_idx` (`politicos_idpoliticos` ASC),
  CONSTRAINT `fk_politicos_has_keywords_politicos1`
    FOREIGN KEY (`politicos_idpoliticos`)
    REFERENCES `gobierno`.`politicos` (`idpoliticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_politicos_has_keywords_keywords1`
    FOREIGN KEY (`keywords_idkeywords`)
    REFERENCES `gobierno`.`keywords` (`idkeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`region` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`region` (
  `idregion` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `compositivos` INT NULL,
  `comnegativos` INT NULL,
  `comneutros` INT NULL,
  `idpoliticos` INT NULL,
  PRIMARY KEY (`idregion`),
  INDEX `fk_region_1_idx` (`idpoliticos` ASC),
  CONSTRAINT `fk_region_1`
    FOREIGN KEY (`idpoliticos`)
    REFERENCES `gobierno`.`politicos` (`idpoliticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobierno`.`comuna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gobierno`.`comuna` ;

CREATE TABLE IF NOT EXISTS `gobierno`.`comuna` (
  `idcomuna` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `compositivos` INT NULL,
  `comnegativos` INT NULL,
  `comneutros` INT NULL,
  `idpoliticos` INT NULL,
  PRIMARY KEY (`idcomuna`),
  INDEX `fk_comuna_1_idx` (`idpoliticos` ASC),
  CONSTRAINT `fk_comuna_1`
    FOREIGN KEY (`idpoliticos`)
    REFERENCES `gobierno`.`politicos` (`idpoliticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gobierno`.`politicos`
-- -----------------------------------------------------
START TRANSACTION;
USE `gobierno`;
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (1, 'Sebastian Piñera', 'Presidente de la Republica', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (2, 'Andrés Chadwick', 'Ministerio del Interior y Seguridad Pública', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (3, 'Roberto Ampuero', 'Ministerio de Relaciones Exteriores', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (4, 'Alberto Espina', 'Ministerio de Defensa Nacional', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (5, 'Felipe Larraín Bascuñán', 'Ministerio de Hacienda', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (6, 'Gonzalo Blumel Mac Iver', 'MInisterio de Secretaría General de la Presidencia', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (7, 'Cecilia Pérez Jara', 'Ministerio de Secretaría General de Gobierno', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (8, 'José Ramón Valente Vias', 'Ministerio de Economía, Fomento y Turismo', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (9, 'Alfredo Moreno Charme', 'Ministerio de Desarrollo Social', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (10, 'Marcela Cubillos Sigall', 'Ministerio de Educación', '2018-08-09', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (11, 'Hernán Larraín Fernández', 'Ministerio de Justicia y Derechos Humanos', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (12, 'Nicolás Monckeberg Díaz', 'Ministerio de Trabajo y Previsión Social', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (13, 'Juan Andrés Fontainer Talavera', 'Ministerio de Obras Públicas', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (14, 'Emilio Santelices Cuevas', 'Ministerio de Salud', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (15, 'Cristián Monckeberg Bruner', 'Ministerio de Vivienda y Urbanismo', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (16, 'Antonio Walker Prieto', 'Ministerio de Agricultura', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (17, 'Baldo Prokurica Prokurica', 'Ministerio de Minería', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (18, 'Gloria Hutt Hesse', 'Ministerio de Transporte y Telecomunicaciones ', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (19, 'Felipe Ward Edwards', 'Ministerio de Bienes Nacionales', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (20, 'Susana Jiménez Schuster', 'Ministerio de Energía', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (21, 'Carolina Schmidt Zaldívar', 'Ministerio de Medio Ambiente', '2018-08-09', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (22, 'Pauline Kantor Pupkin', 'Ministerio de Deporte', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (23, 'Isabel Plá Jarufe', 'Ministerio de la Mujer y la Equidad de Género', '2018-04-11', NULL, 0, 0, 0);
INSERT INTO `gobierno`.`politicos` (`idpoliticos`, `nombre`, `cargo`, `fechainicio`, `fechatermino`, `compositivos`, `comnegativos`, `comneutros`) VALUES (24, 'Consuelo Valdés Chadwick', 'Ministerio de Culturas, las Artes y el Patrimonio', '2018-08-13', NULL, 0, 0, 0);

INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (1, 'Metropolitana', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (2, 'Arica y Parinacota', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (3, 'Tarapacá', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (4, 'Antofagasta', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (5, 'Atacama', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (6, 'Coquimbo', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (7, 'Valparaíso', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (8, "Libertador General Bernardo O'Higgins", 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (9, 'Maule', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (10, 'BioBío', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (11, 'La Araucanía', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (12, 'Los Ríos', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (13, 'Los Lagos', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (14, 'Aysén del General Carlos Ibañez del Campo', 0, 0, 0);
INSERT INTO `gobierno`.`region` (`idregion`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (15, 'Magallanes', 0, 0, 0);

INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (1, 'Santiago', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (2, 'Cerrillos', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (3, 'Cerro Navia', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (4, 'Conchalí', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (5, 'El Bosque', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (6, 'Estación Central', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (7, 'Huechuraba', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (8, "Independencia", 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (9, 'La Cisterna', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (10, 'La Florida', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (11, 'La Granja', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (12, 'La Pintana', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (13, 'La Reina', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (14, 'Las Condes', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (15, 'Lo Barnechea', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (16, 'Lo Espejo', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (17, 'Lo Prado', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (18, 'Macul', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (19, 'Maipú', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (20, 'Ñuñoa', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (21, 'Pedro Aguirre Cerda', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (22, 'Peñalolén', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (23, 'Providencia', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (24, 'Pudahuel', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (25, 'Quilicura', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (26, 'Quinta Normal', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (27, 'Recoleta', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (28, 'Renca', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (29, 'San Joaquín', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (30, 'San Miguel', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (31, 'San Ramón', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (32, 'Vitacura', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (33, 'Colina', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (34, 'Lampa', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (35, 'Til Til', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (36, 'Puente Alto', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (37, 'Pirque', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (38, 'San José de Maipo', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (39, 'Buin', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (40, 'Calera de Tango', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (41, 'Buin', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (42, 'Calera de Tango', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (43, 'Paine', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (44, 'Melipilla', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (45, 'Alhué', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (46, 'Curacaví', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (47, 'María Pinto', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (48, 'San Pedro', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (49, 'Talagante', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (50, 'El Monte', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (51, 'Isla de Maipo', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (52, 'Padre Hurtado', 0, 0, 0);
INSERT INTO `gobierno`.`comuna` (`idcomuna`, `nombre`, `compositivos`, `comnegativos`, `comneutros`) VALUES (53, 'Peñaflor', 0, 0, 0);

COMMIT;
