package cl.usach.gobierno.controllers;

import cl.usach.gobierno.Lucene;
import cl.usach.gobierno.entities.Political;
import cl.usach.gobierno.entities.Localidad;
import cl.usach.gobierno.repositories.PoliticalRepository;
import cl.usach.gobierno.repositories.LocalidadRepository;
import com.mongodb.Block;
import com.mongodb.client.FindIterable;
import com.mongodb.client.model.Filters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import cl.usach.gobierno.MongoConnection;
import org.bson.Document;
import com.mongodb.client.MongoCollection;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


@RestController    // This means that this class is a Controller
@RequestMapping("/localidads")

public class localidadController {
	
	String[] localidadesNombres = {"Arica y Parinacota","Tarapacá","Antofagasta","Atacama","Coquimbo",
			"Valparaíso","Libertador General Bernardo O'Higgins","Maule","BioBío",
			"La Araucanía","Los Ríos","Los Lagos","Aysén del General","Magallanes"};//metropolitana es la ultima
	
	int[] localidadesPoblacion = new int[15];
	int[] localidadesPorcentaje = new int[15];

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private LocalidadRepository localidadRepository;

    @Autowired
    private PoliticalRepository politicalRepository;

    /**
     * Obtiene la informacion de todas las localidades
     * @return OK
     */
    @CrossOrigin
    @GetMapping(path="/")
    public @ResponseBody
    Iterable<Localidad> getAllLocalidad() {
        // This returns a JSON or XML with the users
        return localidadRepository.findAll();
    }
/*
    @CrossOrigin
    @RequestMapping(method = RequestMethod.POST)
    @ResponseBody
    @Transactional
    public ResponseEntity<Localidad> createLocalidad(@RequestBody Localidad resource) {

    	return new ResponseEntity<>(localidadRepository.save(resource), HttpStatus.CREATED);
    }
    */


    /**
     * Obtiene la informacion de un politico dado su id
     * @param id
     * @return OK
     */
    @CrossOrigin
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    @ResponseBody
    public ResponseEntity<Localidad> findOne(@PathVariable("id") Integer id){
        Localidad political = localidadRepository.findById(id);

        if (political == null){
            return new ResponseEntity<>(political, HttpStatus.NOT_FOUND);
        }else{
            return new ResponseEntity<>(political, HttpStatus.OK);
        }
    }

    /**
     * Obtiene los datos para el mapa
     */
    @CrossOrigin
    @RequestMapping(value = "/datos", method = RequestMethod.GET)
    @ResponseBody
    public ArrayList<Map> getDatos() {
    	ArrayList<Map> resultado = new ArrayList<>();
        Lucene luca = new Lucene();
        for(int i = 0; i < 14;i++) {
        	ArrayList<Integer> region = new ArrayList<Integer>();
        	region = luca.RegionSearch(localidadesNombres[i]);
            Map<String, Object> result = new HashMap<String, Object>(2);
            result.put("poblacion", region.get(0));
            result.put("porcentaje", region.get(1));
            resultado.add(result);
        }
        return resultado;
    }

    @CrossOrigin
    @RequestMapping(method = RequestMethod.POST)
    @ResponseBody
    @Transactional
    public ResponseEntity<Localidad> createLocalidad(@RequestBody Localidad resource) {
            return new ResponseEntity<>(localidadRepository.save(resource), HttpStatus.CREATED);
    }
}